name: Weekly Price Update



on:
  schedule:
    - cron: '0 4 * * 1'  # Her Pazartesi saat 04:00 (UTC)
  workflow_dispatch:     # Manuel tetikleme için GitHub arayüzünden

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Repositories klonlanıyor
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkların kurulması
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mesafeler güncelleniyor (Google Maps API)
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: python generate_distances.py

      - name: Fiyatlar güncelleniyor
        run: python main.py

      - name: Değişiklikleri commit et ve pushla
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add prices.json
          git diff --cached --quiet || git commit -m "Haftalık fiyat güncellemesi (auto)"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push
          
        continue-on-error: true  # Eğer değişiklik yoksa commit hatası olmasın
